# Solar System Treks Mosaic Pipeline NAC non-stereo orthomosaic workflow template w/ artifacts (as opposed to volumes)
# Currently very wasteful of bandwidth; file manipulation limitations of using an artifact store lead to excessive
# downloads and uploads

# Process:
#  select nacs
#  download and convert nacs
#      spiceinit
#      lronaccal
#      lronacecho
#  create a mapfile which covers all nacs
#      mosrange
#      cam2map
#      map2map
#      equalizer
#      noseam
#
# Solar System Treks Mosaic Pipeline NAC Stereo workflow template

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generatename: nacpl-mono-
  namespace: default
spec:
  entrypoint: nac-mosaic
  templates:
    - name: nac-mosaic
      inputs:
        #FIXME get rid of these value 0s. Want to be able to submit the WorkflowTemplate
        parameters:
            - name: west
              value: 0
            - name: east
              value: 0
            - name: south
              value: 0
            - name: north
              value: 0
      dag:
        tasks:
          - name: select-nacs
            template: select-nacs
            arguments:
              parameters:
                - name: west
                  value: "{{inputs.parameters.west}}"
                - name: east
                  value: "{{inputs.parameters.east}}"
                - name: south
                  value: "{{inputs.parameters.south}}"
                - name: north
                  value: "{{inputs.parameters.north}}"
          - name: dl-ingest-nac
            templateRef:
              name: dl-ingest-nac
              template: dl-ingest-nac
            arguments:
              parameters:
                - name: prod-id
                  value: "{{item}}"
            withParam: "{{tasks.select-nacs.outputs.result}}"
            continueOn:
              failed: true
            dependencies:
              - select-nacs
          - name: mosrange
            template: mosrange
            dependencies:
              - dl-ingest-nac
          - name: cam2map
            template: cam2map
            arguments:
              parameters:
                - name: prod-id
                  value: "{{item}}"
              artifacts:
                - name: mapfile
                  from: "{{tasks.mosrange.outputs.artifacts.mapfile}}"
            withParam: "{{tasks.select-nacs.outputs.result}}"
            dependencies:
              - mosrange
#          - name: equalize
#            template: equalize
#            dependancies:
#              - cam2map
#          - name: noseam
#            template: equalize
#            dependancies:
#              - equalize

    - name: select-nacs
      inputs:
        parameters:
          - name: west
          - name: east
          - name: south
          - name: north
      script:
        image: lmmp-local/lmmp-container
        imagePullPolicy: IfNotPresent
        command: [bash]
        source: |
          . activate nacpl_env
          python /nacpl/find_nacs_mono.py       \
            --west={{inputs.parameters.west}}   \
            --east={{inputs.parameters.east}}   \
            --south={{inputs.parameters.south}} \
            --north={{inputs.parameters.north}}

    - name: mosrange
      inputs:
        artifacts:
          - name: naccalcubs
            path: /tmp
            s3:
              bucket: my-bucket
              endpoint: minio:9000
              insecure: true
              accessKeySecret:
                name: my-minio-cred
                key: accesskey
              secretKeySecret:
                name: my-minio-cred
                key: secretkey
              key: /nac/mosaics/{{workflow.name}}/
      script:
        image: lmmp-local/lmmp-container
        imagePullPolicy: IfNotPresent
        command: [bash]
        source: |
          . activate nacpl_env
          mkdir -p /mosaics/{{workflow.name}}
          echo /tmp/*.cal.cub > /tmp/mosrange.lst
          mosrange from=/tmp/mosrange.lst to=/mosaics/{{workflow.name}}/mos.map
      outputs:
        artifacts:
          - name: mapfile
            path: /mosaics
            archive:
              none: {}

    - name: cam2map
      inputs:
        parameters:
          - name: prod-id
        artifacts:
          - name: mapfile
            path: /tmp/mos.map
          - name: naccalcub
            path: /tmp/{{workflow.name}}/{{inputs.parameters.prod-id}}.cal.cub
            s3:
              bucket: my-bucket
              endpoint: minio:9000
              insecure: true
              accessKeySecret:
                name: my-minio-cred
                key: accesskey
              secretKeySecret:
                name: my-minio-cred
                key: secretkey
              key: /nac/{{workflow.name}}/{{inputs.parameters.prod-id}}.cal.cub
      script:
        image: lmmp-local/lmmp-container
        imagePullPolicy: IfNotPresent
        command: [bash]
        source: |
          . activate nacpl_env
          cam2map                                           \
            from=/tmp/{{inputs.parameters.prod-id}}.cal.cub \
            to=/tmp/{{inputs.parameters.prod-id}}.map.cub   \
            matchmap=yes                                    \
            map=/tmp/mos.map
      outputs:
        artifacts:
          - name: nacmapcub
            path: /tmp/{{inputs.parameters.prod-id}}.map.cub

#    - name: equalize
#      inputs:
#        artifacts:
#          - name: nacmaps
#            path: /tmp/
#            s3:
#              bucket: my-bucket2
#              endpoint: minio:9000
#              insecure: true
#              accessKeySecret:
#                name: my-minio-cred
#                key: accesskey
#              secretKeySecret:
#                name: my-minio-cred
#                key: secretkey
#              key: /nac/
#      script:
#        image: lmmp-local/lmmp-container
#        imagePullPolicy: IfNotPresent
#        command: [bash]
#        source: |
#          equalizer fromlist=/tmp/mosrange.lst

#          mosrange from

#    - name: cam2map
