# Solar System Treks Mosaic Pipeline NAC non-stereo orthomosaic workflow template w/ volumes

# Process:
#  select nacs
#  download and convert nacs
#      spiceinit
#      lronaccal
#      lronacecho
#  create a mapfile which covers all nacs
#      mosrange
#      cam2map
#      map2map
#      equalizer
#      noseam
#  convert to geotiff
#      cub2tif

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: nacpl-mono-vol
  namespace: default
spec:
  entrypoint: nac-mosaic
  volumes:
    - name: sstmp-data
      persistentVolumeClaim:
        claimName: sstmp-data # This was set up in volumes.yaml
  parallelism: 10
  templates:

    #-------------------------------------------------
    # Dummy template with reusable parts for
    # references in stereo templates. Not to be run.
    #-------------------------------------------------
    - name: dummy-stereo-template
      inputs: &right-left-inps
        parameters:
          - name: right-prod-id
          - name: left-prod-id
      container: &nacpl-container
        image: lmmp-local/lmmp-container
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: sstmp-data  # Should have been created in volumes.yaml
            mountPath: /data/nac

    #---------------------------
    # top-level workflow graph
    #---------------------------
    - name: nac-mosaic
      inputs:
        #FIXME get rid of these value 0s. Want to be able to submit the WorkflowTemplate
        parameters:
          - name: west
            value: 0
          - name: east
            value: 0
          - name: south
            value: 0
          - name: north
            value: 0
      dag:
        tasks:
          - name: select-nacs
            template: select-nacs
            arguments:
              parameters:
                - name: west
                  value: "{{inputs.parameters.west}}"
                - name: east
                  value: "{{inputs.parameters.east}}"
                - name: south
                  value: "{{inputs.parameters.south}}"
                - name: north
                  value: "{{inputs.parameters.north}}"
          - name: dl-ingest-nac
            template: dl-ingest-nac
            arguments:
              parameters:
                - name: prod-id
                  value: "{{item}}"
            withParam: "{{tasks.select-nacs.outputs.result}}"
            continueOn:
              failed: true
            dependencies:
              - select-nacs
          - name: mosrange
            template: mosrange
            arguments:
              parameters:
                - name: prod-id
                  value: "{{item}}"
            dependencies:
              - dl-ingest-nac
          - name: cam2map
            template: cam2map
            arguments:
              parameters:
                - name: prod-id
                  value: "{{item}}"
            withParam: "{{tasks.select-nacs.outputs.result}}"
            dependencies:
              - mosrange
          - name: equalizer
            template: equalizer
            dependencies:
              - cam2map
          - name: noseam
            template: noseam
            dependencies:
              - equalizer
          - name: cub2tif
            template: cub2tif
            dependencies:
              - noseam

    #----------------------
    # Low-level templates
    #----------------------
    - name: select-nacs
      inputs:
        parameters:
          - name: west
          - name: east
          - name: south
          - name: north
      script:
        image: lmmp-local/lmmp-container
        imagePullPolicy: IfNotPresent
        command: [bash]
        source: |
          . activate nacpl_env
          python /nacpl/find_nacs_mono.py       \
            --west={{inputs.parameters.west}}   \
            --east={{inputs.parameters.east}}   \
            --south={{inputs.parameters.south}} \
            --north={{inputs.parameters.north}}

    - name: mosrange
      script:
        <<: *nacpl-container
        command: [bash]
        source: |
          . activate nacpl_env
          echo /data/nac/monomos/{{workflow.name}}/*.cal.cub > /data/nac/monomos/{{workflow.name}}/mosrange.lst
          mosrange from=/data/nac/monomos/{{workflow.name}}/mosrange.lst to=/data/nac/monomos/{{workflow.name}}/mos.map

    #---------------------------
    # download and ingest
    #---------------------------
    # Given a nac product id prod-id, initiate workflow download and injest NAC into ISIS, creating:
    # - Downloaded .IMG file in /data/nac/{{prod-id}}
    # - ISIS-injested .cub file in /data/nac/{{prod-id}}
    - name: dl-ingest-nac
      inputs:
        parameters:
          - name: prod-id
      dag:
        tasks:
          - name: download-nac
            template: download-nac
            arguments:
              parameters:
                - name: prod-id
                  value: "{{inputs.parameters.prod-id}}"
          - name: img2cub
            template: img2cub
            arguments:
              parameters:
                - name: prod-id
                  value: "{{inputs.parameters.prod-id}}"
            dependencies: [download-nac]
          - name: calibrate
            template: calibrate
            arguments:
              parameters:
                - name: prod-id
                  value: "{{inputs.parameters.prod-id}}"
            dependencies: [img2cub]

    # Download a NAC image if doesn't exist and store to / on sstmp-data volume
    # Script downloads to a temporary file and then moves it into place
    - name: download-nac
      inputs:
        parameters:
          - name: prod-id
      retryStrategy:
        limit: 3
      script:
        <<: *nacpl-container
        command: [bash]
        source: |
          . activate nacpl_env
          if ! test -f /data/nac/{{inputs.parameters.prod-id}}.IMG
          then
            python /nacpl/download_NAC.py {{inputs.parameters.prod-id}} /data/nac
          else
            echo "Skipping step because output file already exists"
          fi

    # Convert IMG to ISIS cube if the cube doesn't already exist
    - name: img2cub
      inputs:
        parameters:
          - name: prod-id
      retryStrategy:
        limit: 3

      script:
        <<: *nacpl-container
        command: [bash]
        source: |
          if ! test -f /data/nac/{{inputs.parameters.prod-id}}.cub
          then
            mkdir -p /data/nac/tmp/
            echo "Running lronac2isis FROM=/data/nac/{{inputs.parameters.prod-id}}.IMG TO=/data/nac/tmp/{{inputs.parameters.prod-id}}.cub"
            lronac2isis -v FROM=/data/nac/{{inputs.parameters.prod-id}}.IMG TO=/data/nac/tmp/{{inputs.parameters.prod-id}}.cub
            mv /data/nac/tmp/{{inputs.parameters.prod-id}}.cub /data/nac/
          else
            echo "Skipping step because output file already exists"
          fi

    # Run spiceinit, lronaccal, and lronacecho and produce a .cal.cub if one doesn't already exist.
    # This step also creates a directory monomos/{{workflow.name}} with files specific to this workflow instance.
    - name: calibrate
      inputs:
        parameters:
          - name: prod-id
      retryStrategy:
        limit: 3
      script:
        <<: *nacpl-container
        command: [bash]
        source: |
          if ! test -f /data/nac/{{inputs.parameters.prod-id}}.cal.cub
          then
            spiceinit FROM=/data/nac/{{inputs.parameters.prod-id}}.cub web=yes
            lronaccal FROM=/data/nac/{{inputs.parameters.prod-id}}.cub TO=/tmp/{{inputs.parameters.prod-id}}.cal.cub
            lronacecho FROM=/tmp/{{inputs.parameters.prod-id}}.cal.cub TO=/data/nac/tmp/{{inputs.parameters.prod-id}}.cal.cub
            mv /data/nac/tmp/{{inputs.parameters.prod-id}}.cal.cub /data/nac/{{inputs.parameters.prod-id}}.cal.cub
          else
            echo "Skipping step because output file already exists"
          fi
          mkdir -p /data/nac/monomos/{{workflow.name}}
          # ln -s /data/nac/monomos/{{inputs.parameters.prod-id}}.cal.cub /data/nac/monomos/{{workflow.name}}/{{inputs.parameters.prod-id}}.cal.cub
          cp /data/nac/{{inputs.parameters.prod-id}}.cal.cub /data/nac/monomos/{{workflow.name}}/{{inputs.parameters.prod-id}}.cal.cub

    - name: cam2map
      inputs:
        parameters:
          - name: prod-id
      script:
        <<: *nacpl-container
        command: [ bash ]
        source: |
          . activate nacpl_env
          mkdir -p /data/nac/monomos/{{workflow.name}}/map
          cam2map \
            from=/data/nac/monomos/{{workflow.name}}/{{inputs.parameters.prod-id}}.cal.cub \
            to=/data/nac/monomos/{{workflow.name}}/map/{{inputs.parameters.prod-id}}.map.cub   \
            matchmap=yes \
            map=/data/nac/monomos/{{workflow.name}}/mos.map

    - name: equalizer
      script:
        <<: *nacpl-container
        command: [ bash ]
        source: |
          . activate nacpl_env
          ls -1 /data/nac/monomos/{{workflow.name}}/map/*.map.cub > /tmp/fromlist.lis
          equalizer fromlist=/tmp/fromlist.lis
          mkdir -p /data/nac/monomos/{{workflow.name}}/equalized
          mv /data/nac/monomos/{{workflow.name}}/map/*.equ.cub /data/nac/monomos/{{workflow.name}}/equalized/

    - name: noseam
      script:
        <<: *nacpl-container
        command: [ bash ]
        source: |
          . activate nacpl_env
          echo /data/nac/monomos/{{workflow.name}}/equalized/*.equ.cub > /tmp/fromlist.lis
          noseam from=/tmp/fromlist.lis to=/data/nac/monomos/{{workflow.name}}/mos.cub samples=333 lines=333
      outputs:
        artifacts:
          - name: mosaic.tif
            path: /data/nac/monomos/{{workflow.name}}/mos.tif
            archive:
              none: {}

    - name: cub2tif
      script:
        <<: *nacpl-container
        command: [ bash ]
        source: |
          . activate nacpl_env
          isis2std from=/data/nac/monomos/{{workflow.name}}/mos.cub to=/data/nac/monomos/{{workflow.name}}/mos.tif
      outputs:
        artifacts:
          - name: mosaic.tif
            path: /data/nac/monomos/{{workflow.name}}/mos.tif
            archive:
              none: {}