# Solar System Treks Mosaic Pipeline NAC non-stereo orthomosaic workflow template w/ artifacts (as opposed to volumes)
# Currently very wasteful of bandwidth; file manipulation limitations of using an artifact store lead to excessive
# downloads and uploads

# Process:
#  select nacs
#  download and convert nacs
#      spiceinit
#      lronaccal
#      lronacecho
#  create a mapfile which covers all nacs
#      mosrange
#      cam2map
#      map2map
#      equalizer
#      noseam
#
# Solar System Treks Mosaic Pipeline NAC Stereo workflow template

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generatename: nacpl-mono-
  namespace: default
spec:
  entrypoint: nac-mosaic
  podGC:
    strategy: OnWorkflowCompletion
  templates:
    - name: nac-mosaic
      inputs:
        #FIXME get rid of these value 0s. Want to be able to submit the WorkflowTemplate
        parameters:
            - name: west
              value: 0
            - name: east
              value: 0
            - name: south
              value: 0
            - name: north
              value: 0
      dag:
        tasks:
          - name: select-nacs
            template: select-nacs
            arguments:
              parameters:
                - name: west
                  value: "{{inputs.parameters.west}}"
                - name: east
                  value: "{{inputs.parameters.east}}"
                - name: south
                  value: "{{inputs.parameters.south}}"
                - name: north
                  value: "{{inputs.parameters.north}}"
          - name: dl-ingest-nac
            templateRef:
              name: dl-ingest-nac
              template: dl-ingest-nac
            arguments:
              parameters:
                - name: prod-id
                  value: "{{item}}"
            withParam: "{{tasks.select-nacs.outputs.result}}"
            continueOn:
              failed: true
            dependencies:
              - select-nacs
          - name: mosrange
            template: mosrange
            dependencies:
              - dl-ingest-nac
          - name: cam2map
            template: cam2map
            arguments:
              parameters:
                - name: prod-id
                  value: "{{item}}"
              artifacts:
                - name: mapfile
                  from: "{{tasks.mosrange.outputs.artifacts.mapfile}}"
            withParam: "{{tasks.select-nacs.outputs.result}}"
            dependencies:
              - mosrange
          - name: equalizer
            template: equalizer
            dependencies:
              - cam2map
          - name: noseam
            template: noseam
            dependencies:
              - equalizer

    - name: select-nacs
      inputs:
        parameters:
          - name: west
          - name: east
          - name: south
          - name: north
      script:
        image: lmmp-local/lmmp-container
        imagePullPolicy: IfNotPresent
        command: [bash]
        source: |
          . activate nacpl_env
          python /nacpl/find_nacs_mono.py       \
            --west={{inputs.parameters.west}}   \
            --east={{inputs.parameters.east}}   \
            --south={{inputs.parameters.south}} \
            --north={{inputs.parameters.north}}

    - name: mosrange
      inputs:
        artifacts:
          - name: naccalcubs
            path: /tmp
            s3:
              bucket: my-bucket
              endpoint: minio:9000
              insecure: true
              accessKeySecret:
                name: my-minio-cred
                key: accesskey
              secretKeySecret:
                name: my-minio-cred
                key: secretkey
              key: /nac/mosaics/{{workflow.name}}/
      script:
        image: lmmp-local/lmmp-container
        imagePullPolicy: IfNotPresent
        command: [bash]
        source: |
          . activate nacpl_env
          mkdir -p /mosaics/{{workflow.name}}
          echo /tmp/*.cal.cub > /tmp/mosrange.lst
          mosrange from=/tmp/mosrange.lst to=/mosaics/{{workflow.name}}/mos.map
      outputs:
        artifacts:
          - name: mapfile
            path: /mosaics
            archive:
              none: {}

    - name: cam2map
      inputs:
        parameters:
          - name: prod-id
        artifacts:
          - name: mapfile
            path: /tmp/mos.map
            s3:
              bucket: my-bucket
              endpoint: minio:9000
              insecure: true
              accessKeySecret:
                name: my-minio-cred
                key: accesskey
              secretKeySecret:
                name: my-minio-cred
                key: secretkey
              key: /nac/mosaics/{{workflow.name}}/mos.map

          - name: naccalcub
            path: /tmp/{{workflow.name}}/{{inputs.parameters.prod-id}}.cal.cub
            s3:
              bucket: my-bucket
              endpoint: minio:9000
              insecure: true
              accessKeySecret:
                name: my-minio-cred
                key: accesskey
              secretKeySecret:
                name: my-minio-cred
                key: secretkey
              key: /nac/mosaics/{{workflow.name}}/{{inputs.parameters.prod-id}}.cal.cub
      script:
        image: lmmp-local/lmmp-container
        imagePullPolicy: IfNotPresent
        command: [bash]
        source: |
          . activate nacpl_env
          mkdir -p /mapfiles/{{workflow.name}}
          cam2map                                           \
            from=/tmp/{{workflow.name}}/{{inputs.parameters.prod-id}}.cal.cub \
            to=/mapfiles/{{workflow.name}}/{{inputs.parameters.prod-id}}.map.cub   \
            matchmap=yes                                                      \
            map=/tmp/mos.map
      outputs:
        artifacts:
          - name: mapfiles
            path: /mapfiles
            archive:
              none: {}

    - name: equalizer
      inputs:
        artifacts:
          - name: nacmaps
            path: /tmp
            s3:
              bucket: my-bucket
              endpoint: minio:9000
              insecure: true
              accessKeySecret:
                name: my-minio-cred
                key: accesskey
              secretKeySecret:
                name: my-minio-cred
                key: secretkey
              key: /nac/mapfiles/{{workflow.name}}/
      script:
        image: lmmp-local/lmmp-container
        imagePullPolicy: IfNotPresent
        command: [bash]
        source: |
          . activate nacpl_env
          ls -1 /tmp/*.map.cub > /tmp/fromlist.lis
          equalizer fromlist=/tmp/fromlist.lis
          mkdir -p /equalized
          mv /tmp/*.equ.cub /equalized/{{workflow.name}}
      outputs:
        artifacts:
          - name: equalized
            path: /equalized
            archive:
              none: {}

    - name: noseam
      inputs:
        artifacts:
          - name: equalized
            path: /tmp
            s3:
              bucket: my-bucket
              endpoint: minio:9000
              insecure: true
              accessKeySecret:
                name: my-minio-cred
                key: accesskey
              secretKeySecret:
                name: my-minio-cred
                key: secretkey
              key: /nac/equalized/{{workflow.name}}/
      script:
        image: lmmp-local/lmmp-container
        imagePullPolicy: IfNotPresent
        command: [bash]
        source: |
          . activate nacpl_env
          echo /tmp/*.equ.cub > /tmp/fromlist.lis
          noseam from=/tmp/fromlist.lis to=/tmp/mos.cub
      outputs:
        artifacts:
          - name: mos
            path: /tmp/mos.cub
            archive:
              none: {}