apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: default
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: my-bucket2
      endpoint: minio:9000
      insecure: true
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey
      keyFormat: nac