apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: default
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: my-bucket
      endpoint: minio:9000
      insecure: true
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey
      keyFormat: nac

# Note: these artifact repository settings cause everything to be put in one folder called "nac"
# (due to keyFormat)
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  namespace: default
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: my-bucket
      endpoint: minio:9000
      insecure: true
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey
      keyFormat: nac