apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security-headers
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    #HSTS
    stsIncludeSubdomains: true
    stsSeconds: 31536000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sstmp-ingressroute
  namespace: default
spec:
  routes:
    - match: Host(`trek-k8.jpl.nasa.gov`)
      kind: Rule
      services:
        - kind: Service
          name: argo-server
          port: 2746
          namespace: default
      middlewares:
        - name: security-headers
  tls:
    secretName: trek-k8-tls
    domains:
      - main: trek-k8.jpl.nasa.gov
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: default
  namespace: default

spec:
  cipherSuites:
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256