apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/argoproj/argo/manifests/quick-start/mysql/?ref=release-2.10
  - volumes.yaml
  - moon/ui/k8s-moonui.yaml
  - ingress.yaml
  - moon/wftmpl/nacpl_stereo_vol.yaml
  - moon/wftmpl/nacpl_mono_vol.yaml
  - moon/wftmpl/ui_test.yaml

patches:
  - argo-configmap.yaml