# Skaffold to set up NAC pipeline argo workflow

apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: lmmp-container
    context: moon
  - image: moonui
    context: moon/ui
  tagPolicy:
    sha256: {}
deploy:
  kubectl: 
    manifests: 
    - https://raw.githubusercontent.com/argoproj/argo/release-2.11/manifests/quick-start-mysql.yaml
  kustomize: {}


portForward:
  - resourceType: service
    resourceName: argo-server
    address: 0.0.0.0
    port: 2746
    localPort: 32019
  - resourceType: service
    resourceName: moonui
    address: 0.0.0.0
    port: 1234
    localPort: 32020
