# Skaffold to set up NAC pipeline argo workflow

apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: lmmp-local/lmmp-container
    context: moon
  - image: lmmp-local/moonui
    context: moon/ui
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
deploy:
  kustomize: {}


portForward:
  - resourceType: service
    resourceName: argo-server
    address: 0.0.0.0
    port: 2746
    localPort: 32019
  - resourceType: service
    resourceName: moonui
    address: 0.0.0.0
    port: 1234
    localPort: 32020