# Skaffold to set up NAC pipeline argo workflow

apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: lmmp-container
    context: moon
  - image: moonui
    context: moon/ui
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - argo_crds.yaml
      - moon/wftmpl/nac-mos-mono.yaml
      - moon/wftmpl/nac-mos-stereo.yaml
      - moon/wftmpl/nac-mos-mono-uitest.yaml
      - moon/wftmpl/nac-mos-mono-polygon.yaml
  kustomize: {}
