# Skaffold to set up NAC pipeline argo workflow

apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: lmmp-container
    context: moon
  - image: moonui
    context: moon/ui
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - argo-crds.yaml #Need this so the workflowtemplate CRDS get installed before the workflow templates
  kustomize:
    buildArgs:
      - "--enable_kyaml=false"